# Generated by Django 4.2.1 on 2023-06-15 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CVManagerHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(default='', max_length=100)),
                ('prenume', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('photo', models.ImageField(default=None, upload_to='user_photo')),
                ('city', models.CharField(default='', max_length=500)),
                ('country', models.CharField(default='', max_length=100)),
                ('postcode', models.CharField(default='', max_length=10)),
                ('cv_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_manager.cvmanager')),
            ],
        ),
    ]
