# Generated by Django 4.2.1 on 2023-06-15 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvmanager',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
    ]
