# Generated by Django 4.2.1 on 2023-06-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_manager', '0002_cvmanager_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvmanager',
            name='user',
        ),
    ]
