# Generated by Django 4.2.1 on 2023-06-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_manager', '0003_remove_cvmanager_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvmanager',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('header', 'Header'), ('experience', 'Experience'), ('education', 'Education'), ('skills', 'Skills'), ('final', 'Final')], default='new', max_length=300, verbose_name='Status type'),
        ),
    ]
