# Generated by Django 4.2.1 on 2023-06-15 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_manager', '0004_cvmanager_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvmanagerheader',
            name='cv_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header', to='cv_manager.cvmanager'),
        ),
    ]
