# Generated by Django 4.2.1 on 2023-06-15 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_manager', '0005_alter_cvmanagerheader_cv_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVManagerExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('details', models.TextField()),
                ('cv_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='cv_manager.cvmanager')),
            ],
        ),
    ]
