# Generated by Django 4.2.1 on 2023-06-15 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_manager', '0006_cvmanagerexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVManagerEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('cv_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='cv_manager.cvmanager')),
            ],
        ),
    ]
