# Generated by Django 4.2.1 on 2023-06-15 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_manager', '0007_cvmanagereducation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVManagerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(default='', max_length=100)),
                ('point', models.PositiveIntegerField(default=0)),
                ('cv_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv_manager.cvmanager')),
            ],
        ),
    ]
