# Generated by Django 4.2.1 on 2023-06-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_manager', '0010_alter_cvmanagerheader_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvmanagereducation',
            name='address',
        ),
        migrations.AddField(
            model_name='cvmanagereducation',
            name='details',
            field=models.TextField(default=''),
        ),
    ]
