# Generated by Django 4.2.1 on 2023-06-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_manager', '0011_remove_cvmanagereducation_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvmanagereducation',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cvmanagerexperience',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cvmanagerskill',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
