# Generated by Django 4.2.1 on 2023-06-16 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_skills_templatesname'),
        ('cv_manager', '0012_cvmanagereducation_order_cvmanagerexperience_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvmanager',
            name='nume',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cvmanager',
            name='template_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.templatesname'),
        ),
    ]
