# Generated by Django 4.2.1 on 2023-06-16 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_skills_templatesname'),
        ('cv_manager', '0014_rename_nume_cvmanager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvmanager',
            name='template_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_cv', to='common.templatesname'),
        ),
    ]
