# Generated by Django 4.2.1 on 2023-06-16 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='TemplatesName',
        ),
    ]
